### ISSUE TITLE
Data Model

### ISSUE THREAD

**Issue by chaudharisuresh997** [fly327323571/ProjectManagement#2]
Hi Can you please mention the sql queries for creation of table.
I need to create it by my self to migrate code to plain JDBc project.

**Comment by HelloFy** [comment]
I rebuild this project with some new features , maybe you should re check out it. The create SQL in the SQL directory.Thanks~~

**Comment by chaudharisuresh997** [comment]
@HelloFy did not expect such a quick reply thanks buddy
